# Generated by Django 5.2.7 on 2025-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Flight', 'Flight'), ('Bus', 'Bus'), ('Train', 'Train'), ('Cab', 'Cab')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='travel_images/')),
            ],
        ),
    ]
